name: Zola on GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  getinfo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests
    - name: Run getinfo.py
      run:
        python3 getinfo.py
  build:
    needs: [getinfo]
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
