name: Update atcoder_info and deploy
on:
  schedule:
    - cron: '0 15 * * *'
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: python -m pip install --upgrade pip requests playwright
      - name: Run atcoder_info.py
        run: python3 atcoder_info.py
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
      - name: Setup permissions
        run: sudo chown -R $USER ./public
      - name: Setup browser
        run: python3 -m playwright install chromium
      - name: Run generate_ogp.py
        run: python3 generate_ogp.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: './public'

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: './public'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
