name: Zola on GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  getinfo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests
    - name: Run getinfo.py
      run:
        python3 getinfo.py
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}

        git config --global user.name "GitHub"
        git config --global user.email "noreply@github.com"

        git add static/atcoderCountPython.txt
        git add static/atcoderCountRust.txt
        git add static/atcoderRating.txt
        
        if (git diff --cached --shortstat | grep '[0-9]'); then
          git commit -m "[auto] レートの更新 ${GITHUB_SHA}"
          git push origin HEAD:${GITHUB_REF}
        else
          echo "No changes found"
        fi
  build:
    needs: [getinfo]
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
