name: Zola on GitHub Pages
on:
  schedule:
    - cron: '0 15 * * *'
  push:
    branches:
      - main

jobs:
  update_atcoder_info:
    name: Update atcoder_info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Run atcoder_info.py
        run: python3 atcoder_info.py

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          if (git diff --cached --shortstat | grep '[0-9]'); then
            git commit -m "[GitHub Actions] Update atcoder_info"
            git push origin HEAD:${GITHUB_REF}
          fi

  build:
    needs: [update_atcoder_info]
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git pull

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
